### ISSUE TITLE
Implement typography system

### ISSUE THREAD

**Issue by benjaminpreiss** [frontline-hq/untitled-ui-components#1]
Main goals:

- [ ] Implement classes that describe the whole typography system.
- [ ] Build a documentation page `/typography` that documents these classes: https://www.figma.com/file/IXdTmlM8QvQDClcAKR8V28/Untitled?type=design&node-id=0-1&mode=design

The classes can be defined by using tailwind directives in our libraries own `untltd.css` file that is required to be imported in the projects main css file:

```css
@layer components {
  .btn-blue {
    @apply bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded;
  }
}
```

That way, we can define custom classes within tailwind.

**Comment by NadiemM** [comment]
Nice, here is a small add-on we discussed earlier:

How would a user define the `font-style` and `font-type`?

The most obvious solution would be to configure the style according to the tailwind CSS setup. 

### 1. Add woff2 and woff files

Depending on the framework, add the .woff2 and .woff files corresponding to the font you want to use to your static/public folder.

Example nextjs project:

<img width="224" alt="Schermafbeelding 2023-09-18 om 17 22 38" src="https://github.com/frontline-hq/untitled-ui-components/assets/90260389/f198dc8e-f42a-4103-bba2-bdc3b6e4a8f7">

### 2. Add the corresponding .woff and .woff2 files to the @layer base 

Add the corresponding fonts to the @layer base within your app.css/globals.css file 
```css
@layer base {
  @font-face {
    font-family: "untltd";
    src:
      url("/inter-regular.woff2") format("woff2"),
      url("/inter-regular.woff") format("woff");
    font-weight: 400;
    font-style: normal;
    font-display: swap;
  }
  
  @font-face {
    font-family: "untltd";
    src:
      url("/inter-medium.woff2") format("woff2"),
      url("/inter-medium.woff") format("woff");
    font-weight: 500;
    font-style: normal;
    font-display: swap;
  }
  
  @font-face {
    font-family: "untltd";
    src:
      url("/inter-semibold.woff2") format("woff2"),
      url("/inter-semibold.woff") format("woff");
    font-weight: 600;
    font-style: normal;
    font-display: swap;
  }

  @font-face {
    font-family: "untltd";
    src:
      url("/inter-bold.woff2") format("woff2"),
      url("/inter-bold.woff") format("woff");
    font-weight: 700;
    font-style: normal;
    font-display: swap;
  }
  
}
  ```
  
### 3. Set up your tailwind.config.js

Make sure to set the `font-family` to `untltd` and link to the `untltd` imported fonts, set any other font as backup.

``` js
// tailwind.config.js
module.exports = {
  purge: {
    content: [
      "./pages/**/*.{js,ts,jsx,tsx}",
      "./components/**/*.{js,ts,jsx,tsx}",
    ],
  },
  theme: {
    extend: {
      fontFamily: {
        untltd: ["untltd", "Arial"],
      },
    },
  },
  plugins: [],
}

```
